carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart_item/<int:product_id>/', views.add_cart_item, name='add_cart_item'),
    path('subtract_cart_item/<int:product_id>/<int:cart_item_id>/', views.subtract_cart_item, name='subtract_cart_item'),
    # path('subtract_cart_item/<int:cart_item_id>/', views.subtract_cart_item, name='subtract_cart_item'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout')
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from django.utils.translation import gettext_lazy as _

from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
    path('load_more_review/', views.load_more_review, name='load_more_review'),
    path('searchs/', views.searchs, name='searchs'),
    path('coupon/', views.coupon, name='coupon')
]

carts/models.py
from django.db import models

from store.models import Product, Variation

from accounts.models import Account
# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.quantity * self.product.price

    def __unicode__(self):  # Kinda similar to __str__.
        return self.product

store/models.py
from urllib.parse import MAX_CACHE_SIZE
from django.db import models

from category.models import Category
from django.urls import reverse

from accounts.models import Account

from django.db.models import Avg, Count

# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

    def averageRating(self):
        ratings = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg_rt = 0
        if ratings['average'] is not None:
            avg_rt = float(ratings['average'])
        return avg_rt

    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('review'))
        rv_count = 0
        if reviews['count'] is not None:
            rv_count = int(reviews['count'])
        return rv_count

        # or we can do this
        
        # reviews = ReviewRating.objects.filter(product=self, review__regex=r'[^\s]')
        # return reviews.count()




class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category_choice = (
    ('color', 'Color'),
    ('size', 'Size')
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

    
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject





class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products')

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'






class Coupon(models.Model):
    coupon_code = models.CharField(max_length=200)
    users = models.ManyToManyField(Account, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    sale_off_percent = models.IntegerField(null=True, blank=True)
    stock = models.IntegerField()

    def __str__(self):
        return self.coupon_code

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

carts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from store.models import Product, Variation, Coupon
from .models import Cart, CartItem

from django.http import HttpResponse

from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.decorators import login_required

from django.contrib import messages

# Create your views here.
from datetime import datetime
def _cart_id(request):
    cart = request.session.session_key
    print(f"--------------------------At {datetime.now()}")
    print('\nrequest: \n', request, '\n')
    print('request.session: \n', request.session, '\n')
    print('request.session.session_key: \n', request.session.session_key, '\n')

    if not cart:
        cart = request.session.create()
        print('\n\nNot cart \nrequest.session. ', request.session)
    print('----------------------------------------------------Done----------------------------------------------------\n\n\n')
    return cart



def add_cart_item(request, product_id):
    current_user = request.user

    product = Product.objects.get(id=product_id)

    # If the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        print("\n\n\n\nFrom 'add_cart_item', request.POST: \n", request.POST)
        
        # _______________________get product variations._______________________
        if request.method == 'POST':
            for key, value in request.POST.items():
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        # ________________________________Done_________________________________

        # ________________________________get cart_items.________________________________
        # Chek if cart_item exists
        if CartItem.objects.filter(product=product, user=current_user).exists():
            cart_items = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id_list = []
            for item in cart_items:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id_list.append(item.id)

            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id_list[index]
                cart_item = CartItem.objects.get(id=item_id)
                if cart_item.quantity < cart_item.product.stock:
                    cart_item.quantity += 1
                else:
                    cart_item.quantity = cart_item.product.stock 
                cart_item.save()

            else:
                cart_item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    cart_item.variations.add(*product_variation)
                cart_item.save()

        else:
            cart_item = CartItem.objects.create(product=product, user=current_user, quantity=1)
            if len(product_variation) > 0:
                # cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        # ______________________________________Done______________________________________

        # cart_item.save()
        return redirect('cart')

    # If the user is not authenticated
    else:
        product_variation = []
        print("\n\n\n\nFrom 'add_cart_item', request.POST: \n", request.POST)
        
        # _______________________get product variations._______________________
        if request.method == 'POST':
            for key, value in request.POST.items():
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        # ________________________________Done_________________________________


        # ______________________________get cart._______________________________
        try:
            print("\n--------------------------Call '_cart_id()' in 'carts.views.add_cart_item'.--------------------------")
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            print("Just created a new cart by calling '_cart_id()' in 'carts.views.add_cart_item'.")
            cart = Cart.objects.create(cart_id=_cart_id(request))
            cart.save()
        # _________________________________Done_________________________________


        # ________________________________get cart_items.________________________________

        # Chek if cart_item exists
        if CartItem.objects.filter(product=product, cart=cart).exists():
            cart_items = CartItem.objects.filter(product=product, cart=cart)
            ex_var_list = []
            id_list = []
            for item in cart_items:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id_list.append(item.id)

            if product_variation in ex_var_list:
                index = ex_var_list.index(product_variation)
                item_id = id_list[index]
                cart_item = CartItem.objects.get(id=item_id)
                if cart_item.quantity < cart_item.product.stock:
                    cart_item.quantity += 1
                else:
                    cart_item.quantity = cart_item.product.stock 
                cart_item.save()

            else:
                cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    cart_item.variations.add(*product_variation)
                cart_item.save()

        else:
            cart_item = CartItem.objects.create(product=product, cart=cart, quantity=1)
            if len(product_variation) > 0:
                # cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        # ______________________________________Done______________________________________

        # cart_item.save()
        return redirect('cart')




def subtract_cart_item(request, product_id, cart_item_id):
    print("\n--------------------------Call '_cart_id()' in 'carts.views.subtract_cart_item'.--------------------------")
    product = get_object_or_404(Product, id = product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            
            cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        raise Exception("Check the view 'subtract_cart_item'.")
    return redirect('cart')


# or we can just simply do this. Doing this way required deleting '<int:product_id>/'in urls.py and 'cart_item.product.id' in minus button in cart.html, only send 'cart_item.id'

# def subtract_cart_item(request, cart_item_id):
#     cart_item = CartItem.objects.get(id=cart_item_id)
#     if cart_item.quantity > 1:
#         cart_item.quantity -= 1
#         cart_item.save()
#     else:
#         cart_item.delete()
#     return redirect('cart')




def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id = product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_item = CartItem.objects.get(cart=cart, product=product, id=cart_item_id)
    
    cart_item.delete()
    return redirect('cart')


# or we can simply do this

# def remove_cart_item(request, product_id, cart_item_id):
#     cart_item = CartItem.objects.get(id=cart_item_id)
#     cart_item.delete()
#     return redirect('cart')




def cart(request, total=0, cart_items=0, quantity=0, discount=0):
    tax = 0
    grand_total= 0
    applied = False

    if request.method == 'POST':
        # Discount
        coupon_code = request.POST['coupon_code']
        coupon = Coupon.objects.get(coupon_code=coupon_code)
        coupon_users = coupon.users.all()

        print(f"\n\n\n\n\n\n\n\ncoupon_users: {coupon_users}")
        print(f"request.user.email: {request.user.email}")

        for i in coupon_users:
            if request.user.email == i.email:
                print(f"i.email: {i.email}\n\n\n\n\n\n\n\n")

                discount = coupon.sale_off_percent
                messages.success(request, "Coupon applied successfully.")
                applied = True

        if applied == False:
            messages.error(request, "You haven't get this coupon.")


    try:
        print("\n--------------------------Call '_cart_id()' in 'carts.views.cart'.--------------------------")
        
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id = _cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)


        for cart_item in cart_items:
            total += cart_item.quantity * cart_item.product.price
            quantity += 1
        
        discounted_total = total * ( 1 - discount/100 )

        tax = total * 0.02
        grand_total = discounted_total + tax
    except ObjectDoesNotExist:

templates/store/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% load i18n %}

{% block content %}

<style>
    .recently_viewed {
        width: 100px;
        height: auto;
    }

    .card-width-custom {
        width: 620px;
        text-align: center;
    }


</style>


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap"> 
                    <div class="img-big-wrap mainImage">
                    <center><img src="{{ single_product.images.url }}"></center>
                    </div> <!-- img-big-wrap.// -->
                    
                </article> <!-- gallery-wrap .end// -->

        <ul class="thumb">
            <li>
                <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>

                {% for i in single_product.productgallery_set.all %}
                <a href="{{ i.image.url }}" target="mainImage"><img src="{{ i.image.url }}" alt="Product Image"></a>
                {% endfor %}
            </li>
        </ul>

    </aside>
    <main class="col-md-6 border-left">

    <form action="{% url 'add_cart_item' single_product.id %}" method="POST">
    {% csrf_token %}
      <article class="content-body">
      
      <h2 class="title">{{ single_product.product_name }}</h2>
      <div class="rating-star">
        <span>
            <i class="fa fa-star{% if single_product.averageRating < 0.5 %}-o{% elif single_product.averageRating < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 1.5 %}-o{% elif single_product.averageRating < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 2.5 %}-o{% elif single_product.averageRating < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 3.5 %}-o{% elif single_product.averageRating < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageRating < 4.5 %}-o{% elif single_product.averageRating < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
        </span>
        <span>{{ single_product.countReview }} {% trans 'reviews' %}</span>
    </div>

      <div class="mb-3"> 
          <var class="price h4">${{ single_product.price }}</var> 
      </div> 
      
      <p>{{ single_product.description }}</p>
      
      
      <hr>
          <div class="row">
              <div class="item-option-select">
                  <h6>{% trans 'Choose Color' %}</h6>
                    <select name="color" class="form-control" required>
                      <option value="" disabled selected>{% trans 'Color' %}</option>
                      {% for i in single_product.variation_set.colors %}
                      <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                      {% endfor %}
                    </select>
              </div>
          </div> <!-- row.// -->
          <div class="row">
              <div class="item-option-select">
                  <h6>{% trans 'Select Size' %}</h6>
                    <select name="size" class="form-control" required>
                      <option value="" disabled selected>{% trans 'Size' %}</option>
                      {% for i in single_product.variation_set.sizes %}
                      <option value="{{ i.variation_value | lower }}">{{ i.variation_value | capfirst }}</option>
                      {% endfor %}
                  </select>
                </div>
          </div> <!-- row.// -->
          <hr>
          {% if single_product.stock <= 0 %}
          <h5 class='text-danger'>Out of stock</h5>
          
          {% else %}
          <button type="submit" class="btn  btn-primary"> <span class="text">{% trans 'Add to cart' %}</span> <i class="fas fa-shopping-cart"></i>  </button>

          {% endif %}

      </article> <!-- product-info-aside .// -->
    </form>



    <form action="{% url 'coupon' %}" method="POST">
        {% if coupons %}
                <div class="dropdown_menu">

                    <div class="nav-item dropdown">
                        <button class="btn dropdown-toggle nav-link" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% translate 'Coupon' %}
                        </button>
        
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                            
                                {% for coupon in coupons %} 
                                <form action="{% url 'coupon' %}" method="POST">
                                    {% csrf_token %}
    

                                    <input type="hidden" name="category_slug" value="{{ single_product.category.slug }}">
                                    <input type="hidden" name="product_slug" value="{{ single_product.slug }}">
    

                                    <input type="hidden" name="coupon_code" value="{{ coupon.coupon_code }}">
                                    <button class="dropdown-item" type="submit">{{ coupon.coupon_code | upper }}</button>

                                </form>
                                {% endfor %}
                        </div>
                      </div>

                </div>
        {% endif %}
    </form>



            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->

    {% include 'includes/alerts.html' %}

    <!-- ============================ COMPONENT 1 END .// ================================= -->


    <div class="text-center">    
    {% if recently_viewed_products %}
        <br>
        <br>
        
        <div style="padding-bottom: 0;">
            <h5>Recently Viewed Products</h5>
        </div>

        <div class="card card-width-custom mx-auto" style="padding-bottom: 0; padding-top: 5px;">
            <div class="container">
                <div class="row justify-content-center">
                {% for prod in recently_viewed_products %}
                    <div class="col col-md-1.5 card-product-grid">
                        <a href="{{ prod.get_url }}"><img class="recently_viewed" src="{{ prod.images.url }}" alt="{{ prod.product_name }} Image"></a>
                    </div>
                {% endfor %}
                </div>
            </div>

        </div>

    {% endif %}
    </div> 
    

    <br>
    
    <div class="row">
                <div class="col-md-9">
    
        
        <form action="{% url 'submit_review' single_product.id %}" method="POST">
            {% csrf_token %}
            <h5>{% trans 'Write your Review' %}</h5>
            <div>
            <!-- Rating stars -->
            <label for="">{% trans 'How do you rate this product?' %}</label>
            <br>
            <div class="rate">
            <input type="radio" name="rating" id="rating10" value="5" required><label for="rating10" title="5"></label>
            <input type="radio" name="rating" id="rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
            <input type="radio" name="rating" id="rating8" value="4" required><label for="rating8" title="4"></label>
            <input type="radio" name="rating" id="rating7" value="3.5" required><label for="rating7" title="3.5" class="half"></label>
            <input type="radio" name="rating" id="rating6" value="3" required><label for="rating6" title="3"></label>
            <input type="radio" name="rating" id="rating5" value="2.5" required><label for="rating5" title="2.5" class="half"></label>
            <input type="radio" name="rating" id="rating4" value="2" required><label for="rating4" title="2"></label>
            <input type="radio" name="rating" id="rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
            <input type="radio" name="rating" id="rating2" value="1" required><label for="rating2" title="1"></label>
            <input type="radio" name="rating" id="rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
            </div>
            <br>

            {% trans 'Review Title' %}:
            <input type="text" class="form-control" name="subject">
            <br>
            {% trans 'Review' %}:
            <textarea name="review" rows="4" class="form-control"></textarea>
            <br>
            {% if user.is_authenticated %}
                {% if product_ordered %}
                    <input type="submit" value="{% trans 'Submit Review' %}" class="btn btn-primary">
                {% else %}
                    <P>{% trans 'You must purchase this product to post a review.' %}</P>
                {% endif %}
            {% else %} 
                <p>{% trans 'You must be logged in to post a review.' %} <span><a href="{% url 'login' %}">{% trans 'Login now' %}</a></span></p>
            {% endif %}
            </div>


        </form>

        <br>
<header class="section-heading">
    <h3>{% trans 'Customer Reviews' %} </h3>  
    <span>
        <div class="rating-star">
            <span>
                <i class="fa fa-star{% if single_product.averageRating < 0.5 %}-o{% elif single_product.averageRating < 1 %}-half-o{% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageRating < 1.5 %}-o{% elif single_product.averageRating < 2 %}-half-o{% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageRating < 2.5 %}-o{% elif single_product.averageRating < 3 %}-half-o{% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageRating < 3.5 %}-o{% elif single_product.averageRating < 4 %}-half-o{% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageRating < 4.5 %}-o{% elif single_product.averageRating < 5 %}-half-o{% endif %}" aria-hidden="true"></i>
            </span>
            <span>{{ single_product.countReview }} {% blocktrans count num=single_product.countReview %}review{% plural %}reviews{% endblocktrans %}</span>
        </div>
    </span>
    
</header>

    <div id="loadReviewHere">
<!-- /////////////////////////////////////////////////////////////////////////// -->
<!-- /////////////////////////////////////////////////////////////////////////// -->
<!-- Review display -->


    {% for review in reviews %}
    <article class="box mb-3 review-box">
        <div class="icontext w-100">
            <!-- <img src="{%static './images/avatars/avatar1.jpg'%}" class="img-xs icon rounded-circle"> -->
            <div class="text">
                <span class="date text-muted float-md-right">{{ review.updated_at }} </span>  
                <h6 class="mb-1">{{ review.user.full_name }}</h6>
                <div class="rating-star">
                    <span>
                        <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}" aria-hidden="true"></i>
                    </span>
                </div>
            </div>
        </div> <!-- icontext.// -->
        <div class="mt-3">
            <h6>{{ review.subject }}</h6>
            <p>
                {{ review.review }}
            </p>	
        </div>
    </article>
    {% endfor %}


<!-- /////////////////////////////////////////////////////////////////////////// -->
<!-- /////////////////////////////////////////////////////////////////////////// -->
    </div>
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->


        <div>
            <p class="my-4 text-center">
                <button id="loadMore" this_prod_id="{{ single_product.id }}" data-total="{{ single_product.countReview }}" data-limit="2" class="btn btn-dark btn-sm">Load More<i class="fa fa-sync load-more-icon"></i></button>
            </p>
        </div>


    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/store/review_load.html
{% load static %}

{% for review in reviews %}
        <article class="box mb-3 review-box">
            <div class="icontext w-100">
                <!-- <img src="{%static './images/avatars/avatar1.jpg'%}" class="img-xs icon rounded-circle"> -->
                <div class="text">
                    <span class="date text-muted float-md-right">{{ review.updated_at }} </span>  
                    <h6 class="mb-1">{{ review.user.full_name }}</h6>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o{% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o{% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o{% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o{% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o{% endif %}" aria-hidden="true"></i>
                        </span>
                    </div>
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <h6>{{ review.subject }}</h6>
                <p>
                    {{ review.review }}
                </p>	
            </div>
        </article>
{% endfor %}